### ISSUE TITLE
Azure 晓晓（模版）.itts 的密码错误！

### ISSUE THREAD

**Issue by weigeshen** [yy4382/tts-importer#1]
大佬提供的密码：接着打开它，密码为 yfi.moe；
真的打不开，![image](https://github.com/yy4382/tts-importer/assets/70733077/0b8af985-e6ff-401e-928b-89e5c4c08371)

**Comment by yy4382** [comment]
现在似乎爱阅书香的语音源即使有密码也打不开了，这个方法可能无法使用，我过一会儿会写一个新的方法。

**Comment by yy4382** [comment]
https://tts-importer.yfi.moe/help/ifreetime
还是得自己手动输入
