### ISSUE TITLE
网页版【阅读】v3.28版本支持了http tts 设置，希望可以支持 配置生成

### ISSUE THREAD

**Issue by rodingbaba** [yy4382/tts-importer#2]
大佬你好，网页版【阅读】https://github.com/hectorqin/reader   v3.28版本支持了http tts 设置  ,我有Azure 官方 API，但是不太懂怎样生成http tts的设置，希望你的项目可以支持生成，感谢！

**Comment by yy4382** [comment]
测试了下，直接复制 “阅读（legado）” 的那个配置，复制到他的添加 http tts 的那个里面，然后保存就可以了
![CleanShot 2024-05-06 at 22 01 47@2x](https://github.com/yy4382/tts-importer/assets/55980292/f770a17a-8031-4851-8725-3c8869faabc0)

**Comment by yy4382** [comment]
Help info added in 98d70b4 .
